apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-consumer
  name: hello-world-consumer
  namespace: main-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-consumer
  template:
    metadata:
      labels:
        app: hello-world-consumer
    spec:
      containers:
        - name: hello-world-consumer
          image: strimzi/hello-world-consumer:latest
          env:
            - name: BOOTSTRAP_SERVERS
              value: main-kafka-kafka-bootstrap:9092
            - name: TOPIC
              value: test-topic
            - name: GROUP_ID
              value: hello-world-consumer
            - name: LOG_LEVEL
              value: "INFO"
            - name: MESSAGE_COUNT
              value: "1000000"
