apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: mirror-maker-2
  namespace: dr-kafka
spec:
  version: 2.5.0
  replicas: 1
  connectCluster: "dr-kafka"
  clusters:
  - alias: "main-kafka"
    bootstrapServers: main-kafka-kafka-bootstrap.main-kafka:9092
  - alias: "dr-kafka"
    bootstrapServers: dr-kafka-kafka-bootstrap.dr-kafka:9092
    config:
      config.storage.replication.factor: 3
      offset.storage.replication.factor: 3
      status.storage.replication.factor: 3
      producer.connections.max.idle.ms: 60000
      producer.metadata.max.age.ms: 60000
  mirrors:
  - sourceCluster: "main-kafka"
    targetCluster: "dr-kafka"
    sourceConnector:
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
        sync.topic.configs.enabled: "true"
        sync.topic.configs.interval.seconds: 60
        refresh.topics.interval.seconds: 60
        refresh.groups.interval.seconds: 60
        replication.policy.separator: ""
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
