apiVersion: v1
items:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: kafka
    namespace: openshift-ingress-operator
  spec:
    replicas: 1
    domain: apps-sharded.basedomain.example.net
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
    routeSelector: 
      matchLabels:
        strimzi.io/kind: Kafka
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
